---
env:
  node: true
extends:
  - "airbnb-base"
  - "airbnb-typescript/base"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
rules: {}
